name: Markdown Linter

on: [push, pull_request]

jobs:
  mdlinter:
    name: Lint markdown file
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Lint Markdown files
      uses: avto-dev/markdown-lint@v1
      env: 
        MARKDOWN_CONFIG_FILE: ".markdownlint.json"
      with:
        args: '**/*.md'
